version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/tests"
    schedule:
      interval: "weekly"
